var Q = require("kew");
var _ = require("lodash");

exports.schools = function()
{
    return Q.fcall(function(){
      return schools;
    })
}

exports.school = function(id)
{
  return Q.fcall(function(){
    var s = _.find(schools, {id: id});
    return s || {};
  })
}

var schools = [
{
  "brin": "09YZ",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "directie@kjschool.eu",
  "facebook": "-",
  "id": "7eb22e612f78",
  "language": "Nederlands",
  "latitude": "53.2819665",
  "locationType": "Hoofdvestiging",
  "longitude": "6.1483633",
  "method": "Regulier",
  "municipality": "Kollumerland en Nieuwkruisland",
  "phase": "Primair onderwijs",
  "title": "Kon. Julianaschool",
  "twitter": "-",
  "vestiging": "09YZ00",
  "website": "-"
},
{
  "brin": "16ZD",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "directie@odbseuropa.nl",
  "facebook": "-",
  "id": "ae70c6652eed",
  "language": "Nederlands",
  "latitude": "52.2029661",
  "locationType": "Hoofdvestiging",
  "longitude": "6.8758292",
  "method": "Regulier",
  "municipality": "Enschede",
  "phase": "Primair onderwijs",
  "title": "OBS Europa",
  "twitter": "-",
  "vestiging": "16ZD00",
  "website": "www.obseuropa.nl"
},
{
  "brin": "07IR",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "info@loopplank-alblasserdam.nl",
  "facebook": "-",
  "id": "cd748461de13",
  "language": "Nederlands",
  "latitude": "51.8687673",
  "locationType": "Hoofdvestiging",
  "longitude": "4.6681601",
  "method": "Regulier",
  "municipality": "Alblasserdam",
  "phase": "Primair onderwijs",
  "title": "PCBS De Loopplank",
  "twitter": "-",
  "vestiging": "07IR00",
  "website": "www.loopplank-alblasserdam.nl"
},
{
  "brin": "13WM",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Rooms-Katholiek",
  "e-mail": "info@jeroenschool.scolucas.nl",
  "facebook": "-",
  "id": "7b9dedc1ea90",
  "language": "Nederlands",
  "latitude": "52.0539743",
  "locationType": "Hoofdvestiging",
  "longitude": "4.3161719",
  "method": "Regulier",
  "municipality": "'s-Gravenhage",
  "phase": "Primair onderwijs",
  "title": "Jeroen",
  "twitter": "-",
  "vestiging": "13WM00",
  "website": "www.nldata.nl/jeroen"
},
{
  "brin": "09HW",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "directie@flint.picto.nl",
  "facebook": "-",
  "id": "a239197c0366",
  "language": "Nederlands",
  "latitude": "52.9529578",
  "locationType": "Hoofdvestiging",
  "longitude": "6.6048427",
  "method": "Regulier",
  "municipality": "Aa en Hunze",
  "phase": "Primair onderwijs",
  "title": "Basisschool Ekehaar",
  "twitter": "-",
  "vestiging": "09HW00",
  "website": "www.basisschooldeflint.nl"
},
{
  "brin": "00DY",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Gereformeerd vrijgemaakt",
  "e-mail": "dewegwijzer@vgpo-accretio.nl",
  "facebook": "-",
  "id": "d97ad280d437",
  "language": "Nederlands",
  "latitude": "52.4172528",
  "locationType": "Hoofdvestiging",
  "longitude": "5.8799758",
  "method": "Regulier",
  "municipality": "Elburg",
  "phase": "Primair onderwijs",
  "title": "Basisschool De Wegwijzer",
  "twitter": "-",
  "vestiging": "00DY00",
  "website": "www.wegwijzertharde.nl"
},
{
  "brin": "08CG",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Algemeen bijzonder",
  "e-mail": "info@vdreijdenschool.nl",
  "facebook": "-",
  "id": "4ca81f2115e0",
  "language": "Nederlands",
  "latitude": "52.3469478",
  "locationType": "Hoofdvestiging",
  "longitude": "5.9805323",
  "method": "-",
  "municipality": "Epe",
  "phase": "Primair onderwijs",
  "title": "School voor Speciaal Basisonderwijs vd Reijden",
  "twitter": "-",
  "vestiging": "08CG00",
  "website": "-"
},
{
  "brin": "07ZN",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "info@vco-palmenhof.nl",
  "facebook": "-",
  "id": "6e4ec49c4df5",
  "language": "Nederlands",
  "latitude": "51.5224115",
  "locationType": "Hoofdvestiging",
  "longitude": "3.6063184",
  "method": "Regulier",
  "municipality": "Middelburg",
  "phase": "Primair onderwijs",
  "title": "Palmenhof",
  "twitter": "-",
  "vestiging": "07ZN00",
  "website": "www.vco-palmenhof.nl"
},
{
  "brin": "18TA",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "directie@obsprinsesbeatrix.org",
  "facebook": "-",
  "id": "186f7b882da4",
  "language": "Nederlands",
  "latitude": "52.5274858",
  "locationType": "Hoofdvestiging",
  "longitude": "4.9822818",
  "method": "Regulier",
  "municipality": "Zeevang",
  "phase": "Primair onderwijs",
  "title": "OBS Pr Beatrix",
  "twitter": "-",
  "vestiging": "18TA00",
  "website": "www.obsprinsesbeatrix.org"
},
{
  "brin": "09ZH",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Algemeen bijzonder",
  "e-mail": "directie@lwbeekmanschool.nl",
  "facebook": "-",
  "id": "49fe91cc724b",
  "language": "Nederlands",
  "latitude": "51.686526",
  "locationType": "Hoofdvestiging",
  "longitude": "5.2957362",
  "method": "Regulier",
  "municipality": "'s-Hertogenbosch",
  "phase": "Primair onderwijs",
  "title": "Nutsschool L W Beekman",
  "twitter": "-",
  "vestiging": "09ZH00",
  "website": "www.lwbeekmanschool.nl"
},
{
  "brin": "05XE",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "denoordkaap@vcponoordgroningen.nl",
  "facebook": "-",
  "id": "3a6756718a51",
  "language": "Nederlands",
  "latitude": "53.4163951",
  "locationType": "Hoofdvestiging",
  "longitude": "6.7295604",
  "method": "Overig",
  "municipality": "Eemsmond",
  "phase": "Primair onderwijs",
  "title": "De Noordkaap",
  "twitter": "-",
  "vestiging": "05XE00",
  "website": "www.noordkaapuithuizermeeden.nl"
},
{
  "brin": "10HW",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "wwr@wegwijzerrhoon.nl",
  "facebook": "-",
  "id": "ae551a7db1d2",
  "language": "Nederlands",
  "latitude": "51.853026",
  "locationType": "-",
  "longitude": "4.4257307",
  "method": "Regulier",
  "municipality": "Albrandswaard",
  "phase": "Primair onderwijs",
  "title": "PC Basisshool De Wegwijzer",
  "twitter": "-",
  "vestiging": "10HW00",
  "website": "www.wegwijzerrhoon.nl"
},
{
  "brin": "11EU",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Rooms-Katholiek",
  "e-mail": "directie@agnesschool.nl",
  "facebook": "-",
  "id": "e2457a1fc603",
  "language": "Nederlands",
  "latitude": "52.0301532",
  "locationType": "Hoofdvestiging",
  "longitude": "5.0411953",
  "method": "Regulier",
  "municipality": "IJsselstein",
  "phase": "Primair onderwijs",
  "title": "Agnesschool",
  "twitter": "-",
  "vestiging": "11EU00",
  "website": "www.agnesschool"
},
{
  "brin": "06ST",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "info@cbs-noordster.nl",
  "facebook": "-",
  "id": "543b3d86b173",
  "language": "Nederlands",
  "latitude": "53.2967739",
  "locationType": "Hoofdvestiging",
  "longitude": "5.6519939",
  "method": "Regulier",
  "municipality": "het Bildt",
  "phase": "Primair onderwijs",
  "title": "CBS De Noordster",
  "twitter": "-",
  "vestiging": "06ST00",
  "website": "www.cbs-noordster.nl"
},
{
  "brin": "08TI",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "directie@obsdenbeemd.nl",
  "facebook": "-",
  "id": "f696aa08550a",
  "language": "Nederlands",
  "latitude": "51.8746726",
  "locationType": "Hoofdvestiging",
  "longitude": "4.9765504",
  "method": "Regulier",
  "municipality": "Giessenlanden",
  "phase": "Primair onderwijs",
  "title": "Basisschool Den Beemd",
  "twitter": "-",
  "vestiging": "08TI00",
  "website": "www.obsdenbeemd.nl"
},
{
  "brin": "17SQ",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "info@obsvastert.nl",
  "facebook": "-",
  "id": "25721aa3bd7b",
  "language": "Nederlands",
  "latitude": "52.1945364",
  "locationType": "Hoofdvestiging",
  "longitude": "6.9003157",
  "method": "Regulier",
  "municipality": "Enschede",
  "phase": "Primair onderwijs",
  "title": "Obs Het Vastert",
  "twitter": "-",
  "vestiging": "17SQ00",
  "website": "www.obsvastert.nl"
},
{
  "brin": "05CJ",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Samenwerking",
  "e-mail": "hoogholtje@fidarda.nl",
  "facebook": "-",
  "id": "6769034c10e4",
  "language": "Nederlands",
  "latitude": "53.3580217",
  "locationType": "Hoofdvestiging",
  "longitude": "6.427727",
  "method": "Jenaplan-onderwijs",
  "municipality": "De Marne",
  "phase": "Primair onderwijs",
  "title": "Basisschool Hoogholtje",
  "twitter": "-",
  "vestiging": "05CJ00",
  "website": "www.hoogholtje.nl"
},
{
  "brin": "16KJ",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Openbaar",
  "e-mail": "admin@devlieger-alkmaar.nl",
  "facebook": "-",
  "id": "76175fc3aafb",
  "language": "Nederlands",
  "latitude": "0",
  "locationType": "-",
  "longitude": "0",
  "method": "-",
  "municipality": "Alkmaar",
  "phase": "Primair onderwijs",
  "title": "De Vlieger",
  "twitter": "-",
  "vestiging": "16KJ01",
  "website": "www.devlieger-alkmaar.nl"
},
{
  "brin": "13SF",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "info@wilhelminaschool.pcborijnsburg.nl",
  "facebook": "-",
  "id": "e3baed128441",
  "language": "Nederlands",
  "latitude": "52.1896089",
  "locationType": "Hoofdvestiging",
  "longitude": "4.442454",
  "method": "Regulier",
  "municipality": "Katwijk",
  "phase": "Primair onderwijs",
  "title": "Koningin WilhelminaSchool",
  "twitter": "-",
  "vestiging": "13SF00",
  "website": "www.koninginwilhelminaschool.nl"
},
{
  "brin": "15IT",
  "category": "Publieke school",
  "country": "nl",
  "denomination": "Protestants-Christelijk",
  "e-mail": "info@cosdewereld.nl",
  "facebook": "-",
  "id": "e090e9cf9bc6",
  "language": "Nederlands",
  "latitude": "51.9324038",
  "locationType": "-",
  "longitude": "4.4598204",
  "method": "Regulier",
  "municipality": "Rotterdam",
  "phase": "Primair onderwijs",
  "title": "COS De Wereld",
  "twitter": "-",
  "vestiging": "15IT00",
  "website": "www.cosdewereld.nl"
}
];
